#!/usr/bin/env python3
"""TTF → VLW (Processing/LovyanGFX smooth-font) → C header.

VLW layout, all big-endian int32:
  header[6]  : glyphCount, 11, ptSize, 0, ascent, descent
  glyph[7]×N : codepoint, height, width, advance, topExtent, leftExtent, 0
  bitmaps    : N × (width*height) bytes of 8-bit alpha
"""
import struct, sys, os
from PIL import Image, ImageFont, ImageDraw

def vlw(path, idx, size, charset):
    font = ImageFont.truetype(path, size=size, index=idx)
    asc, dsc = font.getmetrics()
    glyphs, bitmaps = [], []
    for ch in sorted(set(charset)):
        # Render glyph alone on a generous transparent canvas, anchored at a known baseline.
        bbox = font.getbbox(ch)
        if bbox is None:
            l,t,r,b = 0,0,0,0
        else:
            l,t,r,b = bbox
        adv = round(font.getlength(ch))
        gw, gh = max(0,r-l), max(0,b-t)
        if gw==0 or gh==0:                               # space etc.
            glyphs.append((ord(ch),0,0,adv,0,0)); bitmaps.append(b""); continue
        img = Image.new("L",(gw,gh),0)
        ImageDraw.Draw(img).text((-l,-t),ch,font=font,fill=255)
        glyphs.append((ord(ch),gh,gw,adv,asc-t,l))       # topExtent = ascent - bbox.top
        bitmaps.append(img.tobytes())
    out = bytearray()
    out += struct.pack(">6i", len(glyphs), 11, size, 0, asc, dsc)
    for cp,h,w,adv,top,left in glyphs:
        out += struct.pack(">7i", cp,h,w,adv,top,left,0)
    for bm in bitmaps:
        out += bm
    return bytes(out)

def emit_header(name, data, fp):
    fp.write(f"// generated by tools/mkfont.py — {len(data)} bytes\n")
    fp.write(f"#pragma once\n#include <pgmspace.h>\n")
    fp.write(f"const uint8_t {name}[] PROGMEM = {{\n")
    for i in range(0,len(data),16):
        fp.write("  "+",".join(f"0x{b:02X}" for b in data[i:i+16])+",\n")
    fp.write("};\n")

ASCII_UPPER = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
DIGITS      = "0123456789"
ASCII_PRINT = "".join(chr(c) for c in range(32,127))

FONTS = {
  # name             (ttc path,                                   idx, pt, charset)
  "vlw_wordmark":    ("/System/Library/Fonts/Supplemental/Cochin.ttc", 2, 22,
                      "abcdefghijklmnopqrstuvwxyz "),
  "vlw_label":       ("/System/Library/Fonts/Supplemental/Futura.ttc", 0, 14,
                      ASCII_PRINT),
  "vlw_label_sm":    ("/System/Library/Fonts/Supplemental/Futura.ttc", 0, 11,
                      ASCII_PRINT),
  "vlw_serif_sm":    ("/System/Library/Fonts/Supplemental/Cochin.ttc", 2, 14,
                      "abcdefghijklmnopqrstuvwxyz "),
  "vlw_num_lg":      ("/System/Library/Fonts/Supplemental/Futura.ttc", 0, 46,
                      DIGITS),
  "vlw_num_md":      ("/System/Library/Fonts/Supplemental/Futura.ttc", 0, 24,
                      DIGITS+".s "),
}

if __name__=="__main__":
    os.makedirs("src/fonts",exist_ok=True)
    total=0
    for name,(path,idx,pt,cs) in FONTS.items():
        data=vlw(path,idx,pt,cs)
        with open(f"src/fonts/{name}.h","w") as f: emit_header(name,data,f)
        print(f"  {name:14s} {pt:3d}pt {len(cs):3d} glyphs → {len(data):6d} bytes")
        total+=len(data)
    print(f"  total {total} bytes")
