#pragma once
// Anti-aliased VLW fonts, generated by tools/mkfont.py from macOS system faces.
//   Cochin Italic — wordmark / serif labels
//   Futura Medium — letterspaced caps, numerals
#include "fonts/vlw_wordmark.h"
#include "fonts/vlw_serif_sm.h"
#include "fonts/vlw_label.h"
#include "fonts/vlw_label_sm.h"
#include "fonts/vlw_num_lg.h"
#include "fonts/vlw_num_md.h"
